### ISSUE TITLE
安装后云效mona -v报错[BUG]

### ISSUE THREAD

**Issue by owen1011** [bytedance/mona#239]
**bug 描述**
[详细地描述 bug]
使用命令`npm install -g @bytedance/mona-cli@latest`安装成功后
运行`mona -v`报错
```
❯ mona -v
internal/modules/cjs/loader.js:934
  throw err;
  ^

Error: Cannot find module 'ejs'
Require stack:
- C:\Users\Admin\AppData\Roaming\nvm\v14.21.3\node_modules\@bytedance\mona-cli\node_modules\@bytedance\mona-cli-commands\dist\init\utils\template.js
- C:\Users\Admin\AppData\Roaming\nvm\v14.21.3\node_modules\@bytedance\mona-cli\node_modules\@bytedance\mona-cli-commands\dist\init\index.js
- C:\Users\Admin\AppData\Roaming\nvm\v14.21.3\node_modules\@bytedance\mona-cli\dist\buildInPlugins.js
- C:\Users\Admin\AppData\Roaming\nvm\v14.21.3\node_modules\@bytedance\mona-cli\dist\index.js
- C:\Users\Admin\AppData\Roaming\nvm\v14.21.3\node_modules\@bytedance\mona-cli\bin\mona
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:931:15)
    at Function.Module._load (internal/modules/cjs/loader.js:774:27)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.<anonymous> (C:\Users\Admin\AppData\Roaming\nvm\v14.21.3\node_modules\@bytedance\mona-cli\node_modules\@bytedance\mona-cli-commands\dist\init\utils\template.js:45:29)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Admin\\AppData\\Roaming\\nvm\\v14.21.3\\node_modules\\@bytedance\\mona-cli\\node_modules\\@bytedance\\mona-cli-commands\\dist\\init\\utils\\template.js',
    'C:\\Users\\Admin\\AppData\\Roaming\\nvm\\v14.21.3\\node_modules\\@bytedance\\mona-cli\\node_modules\\@bytedance\\mona-cli-commands\\dist\\init\\index.js',
    'C:\\Users\\Admin\\AppData\\Roaming\\nvm\\v14.21.3\\node_modules\\@bytedance\\mona-cli\\dist\\buildInPlugins.js',
    'C:\\Users\\Admin\\AppData\\Roaming\\nvm\\v14.21.3\\node_modules\\@bytedance\\mona-cli\\dist\\index.js',
    'C:\\Users\\Admin\\AppData\\Roaming\\nvm\\v14.21.3\\node_modules\\@bytedance\\mona-cli\\bin\\mona'
  ]
}
```

**版本信息:**

- mona 版本: 0.3.6
- 开发环境: windows11
- node版本(可选): 14.21.3
- npm 版本(可选): 6.14.18

**复现步骤**

**期望结果**

**复现代码**
可复现问题的代码片段/代码仓库
```js
// 复现问题的代码
```

**其他信息**
如截图等可以贴在这里

**Comment by xwchris** [comment]
收到，我们看下，感谢上报~
